package mocks

import (
	"strings"

	mock "github.com/stretchr/testify/mock"
)

// Builder is an autogenerated mock type for the Builder type
type Builder struct {
	mock.Mock
	args string
}

// Args provides a mock function with given fields:
func (_m *Builder) Args() string {
	return strings.TrimSpace(_m.args)
}

// Build provides a mock function with given fields:
func (_m *Builder) Build() {
	_m.Called()
	_m.args = _m.args + "build "
}

// Clean provides a mock function with given fields:
func (_m *Builder) Clean() {
	_m.Called()
	_m.args = _m.args + "clean "
}

// Package provides a mock function with given fields:
func (_m *Builder) Package() {
	_m.args = _m.args + "package "
}

// Run provides a mock function with given fields: _a0
func (_m *Builder) Run(_a0 bool) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SkipTests provides a mock function with given fields:
func (_m *Builder) SkipTests() {

	_m.args = _m.args + "-DskipTests "
}
