// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Builder is an autogenerated mock type for the Builder type
type Builder struct {
	mock.Mock
}

// Args provides a mock function with given fields:
func (_m *Builder) Args() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ModifyArgs provides a mock function with given fields: _a0
func (_m *Builder) ModifyArgs(_a0 []string) {
	_m.Called(_a0)
}

// Run provides a mock function with given fields: _a0
func (_m *Builder) Run(_a0 bool) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
